version: '3'

services:
  shadowsocks:
    build:
      context: .
    image: ghcr.io/getimages/shadowsocks:latest
    restart: always
    network_mode: host
    user: root
    volumes:
      - ./configs:/app/configs
      - ./storage/database:/app/storage/database
      - ./storage/shadowsocks:/app/storage/shadowsocks
      - ./storage/prometheus:/app/storage/prometheus
      - ./web:/app/web
  prometheus:
    image: ghcr.io/getimages/prometheus:v2.46.0
    restart: always
    network_mode: host
    user: root
    command:
      - '--web.enable-lifecycle'
      - '--web.listen-address=127.0.0.1:9420'
      - '--config.file=/prometheus/configs/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--storage.tsdb.retention.time=60d'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./storage/prometheus/configs:/prometheus/configs
      - ./storage/prometheus/data:/prometheus/data
